select B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS 'TOTAL_SALES'
from BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
where YEAR(S.SALES_DATE) = '2022' AND MONTH(S.SALES_DATE) = '01'
group by B.AUTHOR_ID, B.CATEGORY 
order by B.AUTHOR_ID, B.CATEGORY DESC