SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
#parent_item_id에 있지 않는 데이터는 더이상 업그레이드를 할 수 없는 데이터
WHERE ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID FROM ITEM_TREE
    WHERE NOT ISNULL(PARENT_ITEM_ID))
ORDER BY ITEM_ID DESC
