SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E JOIN HR_DEPARTMENT D ON D.DEPT_ID = E.DEPT_ID 
                    JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO 
GROUP BY E.EMP_NO,G.YEAR
HAVING G.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1
# HAVING은 GROUP BY에 들어가있는 필드에대해서만 조건을 걸 수 있다 !