SELECT d.DEPT_ID, d.DEPT_NAME_EN, ROUND(AVG(e.SAL)) AVG_SAL
FROM HR_DEPARTMENT d
JOIN HR_EMPLOYEES e
ON d.DEPT_ID = e.DEPT_ID
GROUP BY d.DEPT_ID
ORDER BY 3 DESC;

-- SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL)) AS AVG_SAL
-- FROM HR_DEPARTMENT D
--          INNER JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
-- GROUP BY D.DEPT_ID
-- ORDER BY 3 DESC;